language: node_js
node_js:
- "10.8"
- "8.12"
dist: trusty
env:
global:
- export NODE_ENV=test
dist: trusty
services:
- postgresql
branches:
except:
- gh-pages
- master
before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
 - npm run mig
script:
- npm test
