export const CLIENTS ={
       "cus_IokscW9UPbH3xm":{"id": "cus_IokscW9UPbH3xm",
                            "comapny": "nanos",
                            "address": 'switzerland',
                            "currency": "usd",
                            "email": 'client1@test.com',
                            "metadata": {},
                            "tax_exempt": "none",
                            "vat_amount":'',
                            "net_amount":"",
                            "gross_amount":"",
                            "phone": null,
                            "campaign_name":""
                        },
       "cus_IokscW9UPbH3sss":{"id": "cus_IokscW9UPbH3sss",
                            "comapny": "wesden",
                            "address": 'germany',
                            "currency": "usd",
                            "email": 'client2@test.com',
                            "metadata": {},
                            "tax_exempt": "exempt",
                            "vat_amount":'',
                            "net_amount":"",
                            "gross_amount":"",
                            "phone": null,
                            "campaign_name":""
                        },
    }
